ifndef FF_ROOT
FF_ROOT		= $(HOME)/fastflow
endif

CXX		= g++-11 -std=c++2a  #-DNO_DEFAULT_MAPPING
INCLUDES	= -I $(FF_ROOT) 
CXXFLAGS  	= -Wall

LDFLAGS 	= -pthread
OPTFLAGS	= -O3 -finline-functions -DNDEBUG

.PHONY: all clean cleanall
.SUFFIXES: .cpp 


%: %.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDES) $(OPTFLAGS) -o $@ $< $(LDFLAGS)

all		: ff

clean		: 
	rm -f ff
cleanall	: clean
	\rm -f *.o *~
